### ISSUE TITLE
Timeout returning JSON in aws-lambda example

### ISSUE THREAD

**Issue by LukeEvans** [http4k/examples#48]
I've followed this tutorial: https://github.com/http4k/examples/tree/master/aws-lambda successfully. However, I added an additional route:

```
    "/json" bind GET to {
        Response(OK).with(jacksonMessageLens of JacksonMessage("Barry", "Hello there!"))
    }
```

Along with with associated object/lens:

```
data class JacksonMessage(val subject: String, val message: String)
val jacksonMessageLens = Body.auto<JacksonMessage>().toLens()
```

After standing up the stack with Pulumi, everything is created and I'm able to hit `/` and `/echo/{message}` through the ApiGateway (using the URL output from Pulumi) as I would expect. However I can only hit `/json` when I run locally. When trying to hit `/json` through the provided URL, I get a timeout.

Since it's working locally, it seems like I'm missing something obvious. Any help would be greatly apprecaited!

**Comment by daviddenton** [comment]
What is going on here is simply that the addition of Jackson to the mix makes the Lambda run out of memory (which is set to 128m by default). The timeout of 15 seconds is also too short for the cold start + classloading.

Up the memory and it will start working again, or even better just use Moshi instead (you'll need to add Kotlin-Reflect as well) and it won't run out. We've taken to using Moshi + Kotshi (for generating adapters) and moving away from Jackson.

**Comment by LukeEvans** [comment]
Thanks @daviddenton! Switching to Moshi solved my problem
