### ISSUE TITLE
Shouldn't the `origignalUriName` cookie be also invalidated here?

### ISSUE THREAD

**Issue by razvn** [http4k/examples#70]
https://github.com/http4k/examples/blob/5fae5638fc9b6802d57d5f79e19a312ab135ad82/oauth/src/main/kotlin/com/example/InMemoryOAuthPersistence.kt#L49

Tried this implementation and I found out that the `originalUriName` cookie persists and wondered if it's on purpose or a missing invalidation step here.

**Comment by daviddenton** [comment]
It's an omission. Good catch, although this isn't meant to be a secure implementation! :)

**Comment by razvn** [comment]
Yes I saw that the Insecure implementation was doing it that's why I wasn't sure if it was on purpose or just a miss. 

For my information, what make the InMemeory version  insecure? The Insecure one in `http4k` I see, but this one not sure what could be.
Thanks

**Comment by daviddenton** [comment]
Actually - it's not so much insecure as "totally unusable in a real context" 😂 .

**Comment by razvn** [comment]
Thanks, works for a demo on a single instance.
